### ISSUE TITLE
怎么运行这软件

### ISSUE THREAD

**Issue by wskydfcu** [genchsusu/xddq-hook#1]
怎么运行这软件

**Comment by Pa55w0rd** [comment]
我下载了fiddler抓不到这个包

**Comment by leung0750** [comment]
不会用不会抓就别搞了，先回去写两年代码再来

**Comment by Pa55w0rd** [comment]
> 不会用不会抓就别搞了，先回去写两年代码再来

不会写代码，会抓包

**Comment by genchsusu** [comment]
1 安装nodejs
npm install -g yarn
然后代码克隆下来后
yarn
yarn start
2 安装Fiddler，配SSL证书，过滤xddq
3 开小程序就可以解析了
